name: ots.golf lower-generality-3
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  benchmark:
    uses: ./.github/workflows/benchmark-track.yml
    with:
      track: lower-generality-3
