name: ots.golf upper-compressions
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  benchmark:
    uses: ./.github/workflows/benchmark-track.yml
    with:
      track: upper-compressions
